# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# https://jekyllrb.com/docs/configuration/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christine Bliven - Babywearing Consultant
email: blivenbabywearing@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Christine Bliven is a babywearing consultant in Zurich, Switzerland, serving both English
  and German communities. Carrying your baby, whether in a sling or a carrier, is emotionally
  and physically beneficial for both baby and parent.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.blivenbabywearing.ch" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
timezone: Europe/Zurich
encoding: utf-8
collections:
  - homepage

# Build settings
markdown: kramdown
github: [metadata]
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-analytics

jekyll_analytics: 
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-112198405-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
